using System.Text;
using RVM.DocForge.Domain.Models;

namespace RVM.DocForge.API.Services.Generators;

public class ReadmeGenerator : IDocumentGenerator
{
    public string Generate(RepositoryAnalysisResult analysis, string projectName)
    {
        var sb = new StringBuilder();

        sb.AppendLine($"# {projectName}");
        sb.AppendLine();

        // Architecture overview
        if (analysis.Architecture.Layers.Count > 0)
        {
            sb.AppendLine("## Architecture");
            sb.AppendLine();
            foreach (var layer in analysis.Architecture.Layers)
            {
                sb.AppendLine($"- **{layer.Name}**: {string.Join(", ", layer.Projects)}");
            }
            sb.AppendLine();
        }

        // Projects
        sb.AppendLine("## Projects");
        sb.AppendLine();
        sb.AppendLine("| Project | Framework | Type | Packages |");
        sb.AppendLine("|---------|-----------|------|----------|");
        foreach (var project in analysis.Projects)
        {
            var pkgCount = project.Packages.Count;
            sb.AppendLine($"| {project.Name} | {project.TargetFramework} | {project.OutputType} | {pkgCount} |");
        }
        sb.AppendLine();

        // Endpoints summary
        if (analysis.Endpoints.Count > 0)
        {
            sb.AppendLine("## API Endpoints");
            sb.AppendLine();
            sb.AppendLine($"Total: **{analysis.Endpoints.Count}** endpoints across **{analysis.Endpoints.Select(e => e.Controller).Distinct().Count()}** controllers.");
            sb.AppendLine();
            foreach (var group in analysis.Endpoints.GroupBy(e => e.Controller))
            {
                sb.AppendLine($"### {group.Key}");
                sb.AppendLine();
                foreach (var ep in group)
                {
                    sb.AppendLine($"- `{ep.HttpMethod} {ep.Route}` — {ep.Action}");
                }
                sb.AppendLine();
            }
        }

        // Entities summary
        if (analysis.Entities.Count > 0)
        {
            sb.AppendLine("## Entities");
            sb.AppendLine();
            sb.AppendLine($"Total: **{analysis.Entities.Count}** types discovered.");
            sb.AppendLine();
            foreach (var entity in analysis.Entities.Take(20))
            {
                var desc = entity.Summary is not null ? $" — {entity.Summary}" : "";
                sb.AppendLine($"- `{entity.Name}` ({entity.Kind}){desc}");
            }
            if (analysis.Entities.Count > 20)
                sb.AppendLine($"- ... and {analysis.Entities.Count - 20} more");
            sb.AppendLine();
        }

        // Services summary
        if (analysis.Services.Count > 0)
        {
            sb.AppendLine("## Services");
            sb.AppendLine();
            sb.AppendLine($"Total: **{analysis.Services.Count}** service interfaces discovered.");
            sb.AppendLine();
        }

        // Dependencies
        if (analysis.Dependencies.Count > 0)
        {
            sb.AppendLine("## Project Dependencies");
            sb.AppendLine();
            sb.AppendLine("```mermaid");
            sb.AppendLine("graph TD");
            foreach (var dep in analysis.Dependencies)
            {
                sb.AppendLine($"    {dep.From} --> {dep.To}");
            }
            sb.AppendLine("```");
            sb.AppendLine();
        }

        sb.AppendLine("---");
        sb.AppendLine($"*Generated by RVM.DocForge at {DateTime.UtcNow:yyyy-MM-dd HH:mm} UTC*");

        return sb.ToString();
    }
}
